def normalize_nbt(input: bytes) -> bytes: ...
def chunk_to_sections_other(nbt: bytes) -> tuple[bytes, bytes]: ...
def sections_other_to_chunk(sections: bytes, other: bytes) -> bytes: ...
def seed_to_sections(seed: int, chunk_x: int, chunk_z: int) -> bytes: ...
def is_chunk_status_full(input: bytes) -> bool: ...
