def normalize_nbt(input: bytes) -> bytes: ...
def chunk_to_sections_other(nbt: bytes) -> tuple[bytes, bytes]: ...
def sections_other_to_chunk(sections: bytes, other: bytes) -> bytes: ...
def seed_to_sections(seed: int, chunk_x: int, chunk_z: int) -> bytes: ...
def seed_to_sections_batch(seed: int, coords: list[tuple[int, int]]) -> list[bytes]: ...
def is_chunk_status_full(input: bytes) -> bool: ...
def chunk_region_encode_batch(
    chunk_nbts: list[bytes], sections_dumps: list[bytes]
) -> list[tuple[bytes, bytes]]: ...
def chunk_region_decode_batch(
    others: list[bytes], sections_deltas: list[bytes], sections_dumps: list[bytes]
) -> list[bytes]: ...
def seed_from_level(level_nbt: bytes) -> int: ...
