from pathlib import Path

def normalize_nbt(input: bytes) -> bytes: ...
def is_chunk_status_full(input: bytes) -> bool: ...
def chunk_region_flatten(
    save_dir: Path,
    repo_dir: Path,
    block_id_mapping: dict[str, str],
) -> list[Path]: ...
def chunk_region_unflatten(
    save_dir: Path,
    repo_dir: Path,
) -> list[Path]: ...
